### ISSUE TITLE
[TS-467] Please update to Python 3.10

### ISSUE THREAD

**Issue by afiorillo** [codacy/codacy-pylint-python3#183]
Hello!

Python 3.10 was released about 2 years ago now. In it, some very helpful syntax has been added to the language, for example [pattern matching](https://peps.python.org/pep-0634/). I am a happy user of Codacy, though when using a `match` statement in my code it raises a SyntaxError which seemingly prevents Pylint from running on the whole project.

This should be resolved by upgrading to Python 3.10, at least I hope it's that simple.

Please let me know if I can provide any additional information.

**Comment by DMarinhoCodacy** [comment]
Hello @afiorillo 

Thanks for your report.

We're upgrading the tool to Python 3.11.

Kind regards
