### ISSUE TITLE
Can you supply us users with the complete .codacyrc you are using for PyLint (Python 3) 2.4.x please ?

### ISSUE THREAD

**Issue by dhensen** [codacy/codacy-pylint-python3#23]
https://github.com/codacy/codacy-pylint-python3/blob/1846c91ed4d6f4bb82a9532b18b97da1e3f8a42d/src/codacy_pylint.py#L109

Can you supply users with the complete .codacyrc you are using for PyLint (Python 3) 2.4.x please ?
I want to pre-run this locally for a sanity check, I keep getting errors that my local pylint never speaks of. (One of them makes sense: unable to import 3rd party libraries, because you dont install my dependencies, stuff like that and more..)

**Comment by lolgab** [comment]
The `.codacyrc` is generated by our infrastructure. We don't have plans at the moment to post it and left users download it sadly.
By the way, having the list of patterns enabled in the website it's easy to write your own:
```json
{
  "files": ["file1.py"],
  "tools": [
    {
      "name": "Pylint Python3",
      "patterns":
        [
           {
              "patternId": "pattern name"
            },
            {
              "patternId": "pattern name"
            }
        ]
    }
  ]
}
```

**Comment by lolgab** [comment]
You can try our experimental [codacy-analysis-cli](https://github.com/codacy/codacy-analysis-cli/) to run our tools locally.
