### ISSUE TITLE
`invalid syntax` using python >= 3.6 type hints

### ISSUE THREAD

**Issue by KIC** [codacy/codacy-pylint-python3#27]
Why does the following signature raise an `invalid syntax`? Maybe I cant see it but it looks like Type Hints are not supported properly.

```
def my_function(a: pd.DataFrame, figsize: Tuple[int, int] = (16, 9)) -> Figure:
  return None
```

**Comment by lolgab** [comment]
Hi @KIC,
Are you sure this is happening with `Pylint (Python 3)` ?
You should disable the other `Pylint` while you use `Pylint (Python 3)`.
I couldn't reproduce your error. We are using Python 3.7 to run Pylint, and it seems to properly parse this code.
By the way, we added support for `mypy` through `Prospector`. You should enable prospector and enable `mypy` from the list of patterns. Go and check it out ;)

**Comment by lolgab** [comment]
Type hints are not officially supported by Pylint: https://github.com/PyCQA/pylint/issues/647
