### ISSUE TITLE
[CY-3063] False positives for W0611 and W0105

### ISSUE THREAD

**Issue by Bibo-Joshi** [codacy/codacy-pylint-python3#73]
Hi.

First off: I'm not sure if this is the right place to ask, but it was the only one I could find. So please excuse me, if I'm wrong to ask here and kindly point me to the right place :)

We're using Codacy to monitor the code quality of our [python-telegram-bot](https://github.com/python-telegram-bot/python-telegram-bot) library. Unfortunately Codacy gives false positives for

* unused-import (W0611) when the imports are used for type hinting. see e.g. [this review](https://app.codacy.com/manual/python-telegram-bot/python-telegram-bot/pullRequest?prid=6317671)
* pointless-string-statement (W0105) for class/module constants. see e.g. [this review](https://app.codacy.com/manual/python-telegram-bot/python-telegram-bot/pullRequest?prid=6324428)

Both of those are not shown when running pylint locally, even without disabeling any warnings globally.
Is there something we can do to make Codacy not mark those lines? Is the something you can do?

I'd be glad for a response :)

**Comment by lolgab** [comment]
Hi @Bibo-Joshi :)
First of all this is a good place to ask questions about our linter integrations :)
Second, it seems that your project minimum supported version is Python 3.6 .
So I suggest you to disable `Pylint` in Codacy which is a legacy version ( 1.9.5 ) that supports both python 2.7 and 3.x where x <= 6, and enable `Pylint (Python 3)` which contains the newest Pylint version and it is for Python 3.x only.

**Comment by Bibo-Joshi** [comment]
Hi, thanks for the response!

> So I suggest you to disable Pylint in Codacy which is a legacy version ( 1.9.5 ) that supports both python 2.7 and 3.x where x <= 6, and enable Pylint (Python 3) which contains the newest Pylint version and it is for Python 3.x only.

You mean like [this](https://docs.codacy.com/repositories-configure/specifying-your-python-version/)? I already tried that (should have mentioned) without seccess. Unfortunately I can't find the report again, because the commit was deleted by rebase … Anyway, I can try again. Or does the setting have to be on master?

> Also, what version of pylint are you running locally?

2.6.0

**Comment by lolgab** [comment]
So I definitely suggest you to use Pylint 2.6.0 even on Codacy by using Pylint (Python 3).

**Comment by lolgab** [comment]
> You mean like this? I already tried that (should have mentioned) without success.

No, I mean that we have two different versions of Pylint in Codacy that are shown as completely different tools:
![image](https://user-images.githubusercontent.com/5793054/96108304-b27c8b80-0edd-11eb-9ad9-a5a28e6a0e7b.png)
As you see in the image, you should disable "PyLint" in the "Code Patterns" section of the UI and enable "PyLint (Python 3)".
The tool named "PyLint" is the legacy version `1.9.5` that supports Python 2.

**Comment by Bibo-Joshi** [comment]
Ah, okay. I had no access to those settings before :D We changed them and rerunning the checks on some commits looks good. I'll have on how new PRs are analyzed :)
One more questions: rerunning the checks doesn't seem to update the issue count for master. Is there a way to run the checks on the complete code base without touching every line?

**Comment by lolgab** [comment]
Codacy should automatically re-run the analysis on the files affected by the configuration change.
In any case, I'm triggering a global cache invalidation from our internal panel so we're sure all the files will be re-analysed.

**Comment by Bibo-Joshi** [comment]
Perfect! The dashboard still shows bumps from the recent commits, but the current issue count is down again.
Thank you so much for your help! I'll close for now and report back, in case something's fishy after all :)

**Comment by lolgab** [comment]
Glad I could help! 😃
